const IMAGES = {
  iceCream: {
    id: 'iceCream',
    poster: 'Dani',
    pod:0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
      username: "username",
      likes: 0,
      reported: false,
      post_id: "post_id",
      comment_date: new Date()}, {text: "text2",
      username: "username2",
      likes: 0,
      reported: false,
      post_id: "post_id",
      comment_date: new Date()},],
    datePosted: new Date()
  },

  cake: {
    id: 'cake',
    poster: 'Gianna',
    pod: 0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
      username: "username",
      likes: 0,
      reported: false,
      post_id: "post_id",
      comment_date: new Date()}, {text: "text2",
      username: "username2",
      likes: 0,
      reported: false,
      post_id: "post_id",
      comment_date: new Date()},],
    datePosted: new Date()
  },

  sydney: {
    id: 'sydney',
    poster: 'Sydney',
    pod: 0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
      username: "username",
      likes: 0,
      reported: false,
      post_id: "post_id",
      comment_date: new Date()}, {text: "text2",
      username: "username2",
      likes: 0,
      reported: false,
      post_id: "post_id",
      comment_date: new Date()},],
    datePosted: new Date()
  },
  iceCream2: {
    id: 'iceCream2',
    poster: 'Dani',
    pod: 0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
    username: "username",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()}, {text: "text2",
    username: "username2",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()},],
    datePosted: new Date()
  },

  cake2: {
    id: 'cake2',
    poster: 'Gianna',
    pod: 0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
    username: "username",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()}, {text: "text2",
    username: "username2",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()},],
    datePosted: new Date()
  },

  sydney2: {
    id: 'sydney2',
    poster: 'Sydney',
    pod: 0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
    username: "username",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()}, {text: "text2",
    username: "username2",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()},],
    datePosted: new Date()
  },
  iceCream3: {
    id: 'iceCream3',
    poster: 'Dani',
    pod:0,
    link: "https://firebasestorage.googleapis.com/v0/b/sapling-grow.appspot.com/o/IMG_1135.jpeg?alt=media&token=85b0ad5d-84f0-4213-a6cc-3e147d45d17c",
    likes: Math.floor(Math.random() * Math.floor(300)),
    comments: [{text: "text",
    username: "username",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()}, {text: "text2",
    username: "username2",
    likes: 0,
    reported: false,
    post_id: "post_id",
    comment_date: new Date()},],
    datePosted: new Date()
  },
}


export {IMAGES}
